version: '3.1'

services:
  
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  
  
  rabbitmq:
    image: rabbitmq:3.8.3-alpine


  orchestrator:
    image: orchestrator:latest
    build:
      context: ./orchestrator
    command: sh -c "sleep 45 && python orchestrator.py"
    ports:
      - "80:5000"
    depends_on:
      - rabbitmq
      - zoo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
  
  master:
    image: master:latest
    build: 
      context: ./master
    command: sh -c "sleep 40 && python master.py"
    links:
      - rabbitmq
      - orchestrator
    depends_on:
      - rabbitmq
      - orchestrator
    restart: on-failure

  slave:
    image: slave:latest
    build: 
      context: ./slave
    command: sh -c "sleep 40 && python slave.py"
    links:
      - rabbitmq
      - zoo
      - orchestrator
    depends_on:
      - rabbitmq
      - zoo
      - orchestrator
    volumes:
      - ./codedata:/code/sdb
    restart: on-failure

  shared_db:
    image: shared_db:latest
    build: 
      context: ./shared_db
    command: sh -c "sleep 40 && python shared_db.py"
    links:
      - rabbitmq
      - orchestrator
    depends_on:
      - rabbitmq
      - orchestrator
    volumes:
      - ./codedata:/code/sdb
    restart: on-failure