version: '3'

services:
  web1:
    build: ./users
    command: python users.py
    restart: always
    ports:
      - "8000:5000"



  web2:
    build: ./rides
    command: python rides.py
    restart: always
    ports:
      - "8080:5000"
